export const groups = [
  { id: '1', groupTitle: 'group 1', color: 'red' },
  { id: '2', groupTitle: 'group 2', color: 'green' },
  { id: '3', groupTitle: 'group 3', color: 'blue' },
  { id: '4', groupTitle: 'group 4', color: 'orange' },
  { id: '5', groupTitle: 'group 5', color: 'purple' },
];

export const tasks = [
  {
    id: '11',
    taskTitle: 'task 11',
    description: 'description 11',
    createData: '12/12/1212',
    createTime: '10.52',
    isEdited: false,
    isDone: false,
    groupId: '1',
  },
  {
    id: '22',
    taskTitle: 'task 22',
    description: 'description 22',
    createData: '12/12/1212',
    createTime: '11.52',
    isEdited: true,
    isDone: false,
    groupId: '1',
  },
  {
    id: '33',
    taskTitle: 'task 33',
    description: 'description 33',
    createData: '12/12/1212',
    createTime: '12.52',
    isEdited: false,
    isDone: true,
    groupId: '2',
  },
  {
    id: '44',
    taskTitle: 'task 44',
    description: 'description 44',
    createData: '12/12/1212',
    createTime: '13.52',
    isEdited: true,
    isDone: true,
    groupId: '2',
  },
  {
    id: '55',
    taskTitle: 'task 55',
    description: 'description 55',
    createData: '12/12/1212',
    createTime: '14.52',
    isEdited: false,
    isDone: false,
    groupId: '3',
  },
  {
    id: '66',
    taskTitle: 'task 66',
    description: 'description 66',
    createData: '12/12/1212',
    createTime: '15.52',
    isEdited: false,
    isDone: true,
    groupId: '3',
  },
  {
    id: '77',
    taskTitle: 'task 77',
    description: 'description 77',
    createData: '12/12/1212',
    createTime: '16.52',
    isEdited: false,
    isDone: false,
    groupId: '4',
  },
  {
    id: '88',
    taskTitle: 'task 88',
    description: 'description 88',
    createData: '12/12/1212',
    createTime: '17.52',
    isEdited: true,
    isDone: false,
    groupId: '4',
  },
  {
    id: '99',
    taskTitle: 'task 99',
    description: 'description 99',
    createData: '12/12/1212',
    createTime: '18.52',
    isEdited: false,
    isDone: false,
    groupId: '5',
  },
  {
    id: '100',
    taskTitle: 'task 100',
    description: 'description 100',
    createData: '12/12/1212',
    createTime: '19.52',
    isEdited: true,
    isDone: true,
    groupId: '5',
  },
];
